export interface Brand {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  categories: string[];
  logo: string;
  featured: boolean;
}

export const brands: Brand[] = [
  {
    slug: "optika",
    name: "Optika",
    tagline: "Precision optical instruments",
    description: "Italian manufacturer of microscopes and optical instruments for research, education, and clinical use.",
    categories: ["Microscopy", "Optics"],
    logo: "/brands/optika.png",
    featured: true,
  },
  {
    slug: "adam-equipment",
    name: "Adam Equipment",
    tagline: "Weighing & moisture analysis",
    description: "Precision balances, moisture analysers, and weighing solutions for laboratory and industrial use.",
    categories: ["Balances", "Moisture Analysis"],
    logo: "/brands/adam.png",
    featured: true,
  },
  {
    slug: "adwa",
    name: "Adwa Instruments",
    tagline: "Electrochemical measurement",
    description: "Portable and bench-top instruments for pH, conductivity, dissolved oxygen, and water quality measurement.",
    categories: ["Electrochemistry", "Water Testing"],
    logo: "/brands/adwa.png",
    featured: true,
  },
  {
    slug: "velp",
    name: "VELP",
    tagline: "Analytical instruments for food & environment",
    description: "Italian manufacturer of analytical instruments for nitrogen determination, extraction, and environmental testing.",
    categories: ["Kjeldahl", "Extraction", "Food Analysis"],
    logo: "/brands/velp.png",
    featured: true,
  },
  {
    slug: "bioer",
    name: "Bioer",
    tagline: "Molecular biology instruments",
    description: "Thermal cyclers, real-time PCR systems, and molecular biology equipment for research and diagnostics.",
    categories: ["PCR", "Molecular Biology"],
    logo: "/brands/bioer.png",
    featured: true,
  },
  {
    slug: "erichsen",
    name: "Erichsen",
    tagline: "Material & coating testing",
    description: "German manufacturer of instruments for paint, coatings, and material testing — hardness, adhesion, and film application.",
    categories: ["Materials Testing", "Coatings", "Paint"],
    logo: "/brands/erichsen.png",
    featured: true,
  },
  {
    slug: "staycold",
    name: "Staycold",
    tagline: "Cold storage & refrigeration",
    description: "Commercial and laboratory refrigeration solutions — freezers, cold rooms, and temperature-controlled storage.",
    categories: ["Refrigeration", "Cold Storage"],
    logo: "/brands/staycold.png",
    featured: false,
  },
  {
    slug: "haier-medical",
    name: "Haier Medical",
    tagline: "Medical-grade cold chain solutions",
    description: "Medical refrigerators, ultra-low temperature freezers, and blood bank equipment for clinical and research environments.",
    categories: ["Medical Refrigeration", "Cold Chain"],
    logo: "/brands/haier.png",
    featured: false,
  },
  {
    slug: "cid",
    name: "CID Inc.",
    tagline: "Plant science instruments",
    description: "Specialised instruments for plant physiology, root analysis, and photosynthesis measurement.",
    categories: ["Plant Science", "Agriculture"],
    logo: "/brands/cid.png",
    featured: false,
  },
  {
    slug: "hydrolab",
    name: "Hydrolab",
    tagline: "Water quality monitoring",
    description: "Multi-parameter water quality instruments for environmental monitoring, field testing, and laboratory analysis.",
    categories: ["Water Testing", "Environmental"],
    logo: "/brands/hydrolab.png",
    featured: false,
  },
  {
    slug: "ika",
    name: "IKA",
    tagline: "Mixing, heating & reaction technology",
    description: "IKA laboratory equipment for mixing, stirring, heating, and process technology — from hotplates to large-scale reactors.",
    categories: ["Mixing", "Heating", "Reaction"],
    logo: "/brands/ika.png",
    featured: true,
  },
  {
    slug: "consort",
    name: "Consort",
    tagline: "Electrophoresis & power supplies",
    description: "Belgian manufacturer of electrophoresis equipment and laboratory power supplies for life science research.",
    categories: ["Electrophoresis", "Power Supplies"],
    logo: "/brands/consort.png",
    featured: false,
  },
  {
    slug: "infitek",
    name: "Infitek",
    tagline: "Infrared spectroscopy",
    description: "FTIR spectrometers and near-infrared instruments for chemical analysis and quality control.",
    categories: ["Spectroscopy", "FTIR"],
    logo: "/brands/infitek.png",
    featured: false,
  },
  {
    slug: "advance-lab-global",
    name: "Advance Lab Global",
    tagline: "Laboratory consumables & equipment",
    description: "Comprehensive range of laboratory consumables, glassware, and general laboratory equipment.",
    categories: ["Consumables", "Glassware"],
    logo: "/brands/advancelab.png",
    featured: false,
  },
  {
    slug: "interscience",
    name: "Interscience",
    tagline: "Microbiology instruments",
    description: "French manufacturer of instruments for food microbiology — stomachersand colony counters for rapid detection.",
    categories: ["Microbiology", "Food Safety"],
    logo: "/brands/interscience.png",
    featured: true,
  },
  {
    slug: "labfriend",
    name: "LabFriend",
    tagline: "Laboratory supplies & consumables",
    description: "Broad range of laboratory supplies, safety equipment, and consumables for research and industrial laboratories.",
    categories: ["Consumables", "Safety", "Supplies"],
    logo: "/brands/labfriend.png",
    featured: false,
  },
  {
    slug: "kruss",
    name: "KRÜSS Scientific",
    tagline: "Surface science & tensiometry",
    description: "German manufacturer of tensiometers, contact angle instruments, and foam analysers for surface science research.",
    categories: ["Surface Science", "Tensiometry"],
    logo: "/brands/kruss.png",
    featured: false,
  },
  {
    slug: "scientific-sa",
    name: "Scientific (SA)",
    tagline: "South African laboratory distribution",
    description: "Local distributor of a broad range of laboratory instruments and consumables across South Africa.",
    categories: ["Distribution", "Instruments"],
    logo: "/brands/scientific.png",
    featured: false,
  },
  {
    slug: "grupo-selecta",
    name: "Grupo Selecta",
    tagline: "Heating & temperature equipment",
    description: "Spanish manufacturer of laboratory heating equipment — baths, ovens, incubators, and autoclaves.",
    categories: ["Heating", "Temperature Control"],
    logo: "/brands/selecta.png",
    featured: false,
  },
  {
    slug: "scotsman",
    name: "Scotsman",
    tagline: "Ice & cold water dispensing",
    description: "Commercial ice machines and cold beverage dispensing equipment for laboratories and healthcare facilities.",
    categories: ["Ice Machines", "Refrigeration"],
    logo: "/brands/scotsman.png",
    featured: false,
  },
  {
    slug: "primelab",
    name: "Prime Lab",
    tagline: "Portable water analysis",
    description: "Portable photometers and water analysis kits for rapid, accurate water quality testing in the field.",
    categories: ["Water Testing", "Portable Instruments"],
    logo: "/brands/primelab.png",
    featured: false,
  },
  {
    slug: "wiggens",
    name: "Wiggens",
    tagline: "Mixing & stirring instruments",
    description: "German-engineered vortex mixers, magnetic stirrers, and shakers for laboratory mixing applications.",
    categories: ["Mixing", "Stirring"],
    logo: "/brands/wiggens.png",
    featured: false,
  },
  {
    slug: "pol-eko",
    name: "Pol-Eko",
    tagline: "Climatic & laboratory chambers",
    description: "Polish manufacturer of climatic chambers, incubators, freezers, and drying ovens for laboratory and industrial use.",
    categories: ["Climatic Chambers", "Incubators", "Ovens"],
    logo: "/brands/poleko.png",
    featured: true,
  },
  {
    slug: "mrc-lab",
    name: "MRC Lab",
    tagline: "Laboratory instruments & equipment",
    description: "Comprehensive range of laboratory instruments for analytical, clinical, and research applications.",
    categories: ["Analytical", "Clinical", "Research"],
    logo: "/brands/mrc.png",
    featured: true,
  },
];

export const featuredBrands = brands.filter((b) => b.featured);
